spring:
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:h2:mem:std;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        username: std
        password:
    h2:
        console:
            enabled: false
    jpa:
        database: H2
        properties:
            hibernate.id.new_generator_mappings: true
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
    rest:
      client:
        services:
          tangent: http://staging.tangent.tngnt.co/
          
            
server:
    port: 8080

application:
    security:
        authentication:
            jwt:
                secret: my-secret-token-to-change-in-production
                # Token is valid 24 hours
                token-validity-in-seconds: 86400
                token-validity-in-seconds-for-remember-me: 2592000

